# Generated by Django 3.1.5 on 2026-04-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0003_auto_20260413_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director_gold',
            name='status',
            field=models.CharField(choices=[('Complete', 'COMPLETE'), ('Incomplete', 'INCOMPLETE'), ('Reject', 'REJECT'), ('Accept', 'ACCEPT'), ('ACCEPT', 'Accept'), ('REJECT', 'Reject'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('UNDER_REVIEW', 'Under Review'), ('SUBMITTED', 'Submitted'), ('FORWARDED', 'Forwarded'), ('NEEDS_INFO', 'Needs Info'), ('APPROVED', 'Approved')], default='INCOMPLETE', max_length=20),
        ),
        migrations.AlterField(
            model_name='director_silver',
            name='status',
            field=models.CharField(choices=[('Complete', 'COMPLETE'), ('Incomplete', 'INCOMPLETE'), ('Reject', 'REJECT'), ('Accept', 'ACCEPT'), ('ACCEPT', 'Accept'), ('REJECT', 'Reject'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('UNDER_REVIEW', 'Under Review'), ('SUBMITTED', 'Submitted'), ('FORWARDED', 'Forwarded'), ('NEEDS_INFO', 'Needs Info'), ('APPROVED', 'Approved')], default='INCOMPLETE', max_length=20),
        ),
        migrations.AlterField(
            model_name='mcm',
            name='status',
            field=models.CharField(choices=[('Complete', 'COMPLETE'), ('Incomplete', 'INCOMPLETE'), ('Reject', 'REJECT'), ('Accept', 'ACCEPT'), ('ACCEPT', 'Accept'), ('REJECT', 'Reject'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('UNDER_REVIEW', 'Under Review'), ('SUBMITTED', 'Submitted'), ('FORWARDED', 'Forwarded'), ('NEEDS_INFO', 'Needs Info'), ('APPROVED', 'Approved')], default='INCOMPLETE', max_length=20),
        ),
        migrations.AlterField(
            model_name='proficiency_dm',
            name='status',
            field=models.CharField(choices=[('Complete', 'COMPLETE'), ('Incomplete', 'INCOMPLETE'), ('Reject', 'REJECT'), ('Accept', 'ACCEPT'), ('ACCEPT', 'Accept'), ('REJECT', 'Reject'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('UNDER_REVIEW', 'Under Review'), ('SUBMITTED', 'Submitted'), ('FORWARDED', 'Forwarded'), ('NEEDS_INFO', 'Needs Info'), ('APPROVED', 'Approved')], default='INCOMPLETE', max_length=20),
        ),
        migrations.AlterField(
            model_name='singleparent',
            name='status',
            field=models.CharField(choices=[('Complete', 'COMPLETE'), ('Incomplete', 'INCOMPLETE'), ('Reject', 'REJECT'), ('Accept', 'ACCEPT'), ('ACCEPT', 'Accept'), ('REJECT', 'Reject'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('UNDER_REVIEW', 'Under Review'), ('SUBMITTED', 'Submitted'), ('FORWARDED', 'Forwarded'), ('NEEDS_INFO', 'Needs Info'), ('APPROVED', 'Approved')], default='INCOMPLETE', max_length=20),
        ),
    ]
