# Generated by Django 3.1.5 on 2026-04-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0004_auto_20260413_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcm',
            name='application_form',
            field=models.FileField(blank=True, null=True, upload_to='scholarships/mcm/application_form/'),
        ),
        migrations.AddField(
            model_name='mcm',
            name='caste_certificate',
            field=models.FileField(blank=True, null=True, upload_to='scholarships/mcm/caste_certificate/'),
        ),
        migrations.AddField(
            model_name='mcm',
            name='death_certificate',
            field=models.FileField(blank=True, null=True, upload_to='scholarships/mcm/death_certificate/'),
        ),
        migrations.AddField(
            model_name='mcm',
            name='generated_pdf',
            field=models.FileField(blank=True, null=True, upload_to='scholarships/mcm/generated_pdf/'),
        ),
        migrations.AddField(
            model_name='mcm',
            name='mother_income_certificate',
            field=models.FileField(blank=True, null=True, upload_to='scholarships/mcm/mother_income_certificate/'),
        ),
        migrations.AddField(
            model_name='mcm',
            name='parent_status',
            field=models.CharField(blank=True, choices=[('Both Parents Alive', 'Both Parents Alive'), ('Single Parent', 'Single Parent')], default='Both Parents Alive', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mcm',
            name='score_card',
            field=models.FileField(blank=True, null=True, upload_to='scholarships/mcm/score_card/'),
        ),
        migrations.AddField(
            model_name='mcm',
            name='undertaking_form',
            field=models.FileField(blank=True, null=True, upload_to='scholarships/mcm/undertaking_form/'),
        ),
    ]
