# Generated by Django 3.1.5 on 2026-04-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0005_auto_20260419_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcm',
            name='single_parent',
            field=models.BooleanField(default=False),
        ),
    ]
