# Generated by Django 3.1.5 on 2026-04-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0007_auto_20260419_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcm',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mcm',
            name='jee_rank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
