# Generated by Django 3.1.5 on 2026-04-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0008_auto_20260419_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcm',
            name='Aadhar_card',
            field=models.FileField(blank=True, default='', null=True, upload_to='scholarships/mcm/aadhar_card/'),
        ),
        migrations.AlterField(
            model_name='mcm',
            name='Affidavit',
            field=models.FileField(blank=True, default='', null=True, upload_to='scholarships/mcm/affidavit/'),
        ),
        migrations.AlterField(
            model_name='mcm',
            name='Bank_details',
            field=models.FileField(blank=True, default='', null=True, upload_to='scholarships/mcm/bank_details/'),
        ),
        migrations.AlterField(
            model_name='mcm',
            name='Fee_Receipt',
            field=models.FileField(blank=True, default='', null=True, upload_to='scholarships/mcm/fee_receipt/'),
        ),
        migrations.AlterField(
            model_name='mcm',
            name='Marksheet',
            field=models.FileField(blank=True, default='', null=True, upload_to='scholarships/mcm/marksheet/'),
        ),
    ]
