# Generated by Django 3.1.5 on 2026-04-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0011_auto_20260419_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcm',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='singleparent',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
