# Generated by Django 3.1.5 on 2026-04-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0012_auto_20260419_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleparent',
            name='Affidavit',
            field=models.FileField(blank=True, null=True, upload_to='scholarships/single_parent/affidavit/'),
        ),
        migrations.AddField(
            model_name='singleparent',
            name='Bank_details',
            field=models.FileField(blank=True, null=True, upload_to='scholarships/single_parent/bank_details/'),
        ),
        migrations.AddField(
            model_name='singleparent',
            name='Fee_Receipt',
            field=models.FileField(blank=True, null=True, upload_to='scholarships/single_parent/fee_receipt/'),
        ),
        migrations.AddField(
            model_name='singleparent',
            name='Marksheet',
            field=models.FileField(blank=True, null=True, upload_to='scholarships/single_parent/marksheet/'),
        ),
        migrations.AddField(
            model_name='singleparent',
            name='application_form',
            field=models.FileField(blank=True, null=True, upload_to='scholarships/single_parent/application_form/'),
        ),
        migrations.AddField(
            model_name='singleparent',
            name='caste_certificate',
            field=models.FileField(blank=True, null=True, upload_to='scholarships/single_parent/caste_certificate/'),
        ),
        migrations.AddField(
            model_name='singleparent',
            name='cpi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='singleparent',
            name='last_sem_result',
            field=models.FileField(blank=True, null=True, upload_to='scholarships/single_parent/last_sem_result/'),
        ),
        migrations.AddField(
            model_name='singleparent',
            name='mother_income_certificate',
            field=models.FileField(blank=True, null=True, upload_to='scholarships/single_parent/mother_income_certificate/'),
        ),
        migrations.AddField(
            model_name='singleparent',
            name='score_card',
            field=models.FileField(blank=True, null=True, upload_to='scholarships/single_parent/score_card/'),
        ),
        migrations.AddField(
            model_name='singleparent',
            name='undertaking_form',
            field=models.FileField(blank=True, null=True, upload_to='scholarships/single_parent/undertaking_form/'),
        ),
    ]
